POST /test HTTP/1.1
Host: localhost
Accept: */*
Accept-Encoding: gzip
Content-Length: 824
Content-Type: application/json
User-Agent: Go-http-client/1.1

{
	"signature": {
		"token": "809d12a32a517d6ff797904558564411e339e3742e97b0d6bf",
		"timestamp": "1738097854",
		"signature": "foo"
	},
	"event-data": {
		"id": "-Agny091SquKnsrW2NEKUA",
		"timestamp": 1521233123.501324,
		"log-level": "warn",
		"event": "complained",
		"envelope": {
			"sending-ip": "173.193.210.33"
		},
		"flags": {
			"is-test-mode": false
		},
		"message": {
			"headers": {
				"to": "Alice <alice@example.com>",
				"message-id": "20110215055645.25246.63817@mg.example.com",
				"from": "Bob <bob@mg.example.com>",
				"subject": "Test complained webhook"
			},
			"attachments": [],
			"size": 111
		},
		"recipient": "alice@example.com",
		"campaigns": [],
		"tags": [
			"my_tag_1",
			"my_tag_2"
		],
		"user-variables": {
			"my_var_1": "Mailgun Variable #1",
			"my-var-2": "awesome"
		}
	}
}
